### ISSUE TITLE
Group, ungroup, and duplicate buttons should be cyan 

### ISSUE THREAD

**Issue by SomeDudeOnGithub** [andreja6/G3D-Fun#115]
![image-016 - Copy](https://user-images.githubusercontent.com/80745237/197398353-e111c34e-870a-47fd-af85-a71605e6a312.png)
![image-015 - Copy](https://user-images.githubusercontent.com/80745237/197398424-7508dc91-03de-413f-a49f-6234a13de411.png)

**Comment by Vulpovile** [comment]
Interesting

**Comment by Vulpovile** [comment]
This has been updated in some PR
