### ISSUE TITLE
characters from 2005 roblox

### ISSUE THREAD

**Issue by dani814** [andreja6/G3D-Fun#121]
hi, can you please add character from 2005 roblox?, and maybe where you can play with a character,
this is a suggestion, not a issue.

**Comment by dani814** [comment]
i typed in dynablocks instead of 2005 roblox on accident sorry.

**Comment by Bitl** [comment]
2005 roblox never had characters. Characters started appearing in 2006 when the game got a revamp

No reason to do this unless the maintainer/s decide to do 2006, which I somewhat doubt will happen

**Comment by dani814** [comment]
i wonder why did they go from goblocks to dynablocks and then to roblox

**Comment by dani814** [comment]
just like hello neighbor with 3 betas
