### ISSUE TITLE
Sky should used the compressed texture that old clients use

### ISSUE THREAD

**Issue by SomeDudeOnGithub** [andreja6/G3D-Fun#125]
![compsky](https://github.com/Vulpovile/Blocks3D/assets/80745237/6762bb05-1a92-4ca2-ad60-8ec70b6668d2)

**Comment by brannanz** [comment]
It isn't really known if they compressed it in 2005 or not.

**Comment by Vulpovile** [comment]
Yeah, and this is the default skybox for Graphics3D, so it's possible they didn't compress it until quite a bit later. If further evidence is found, then we can always use the compressed version later, so thanks for the input!
