### ISSUE TITLE
The site doesn't work

### ISSUE THREAD

**Issue by EmanuelAbate6565** [andreja6/G3D-Fun#126]
Whenever i open the app, it opens up blocks3d.com, except it seems like that website doesn't exist as every singular time i open up the website, it doesn't load, making the game seemingly unplayable, please fix this issue

**Comment by Vulpovile** [comment]
Run the editor, not the player, the player was intended to use Internet explorer to load games originally but Microsoft went all totalitarian dictator and doesn't let you do that anymore

**Comment by EmanuelAbate6565** [comment]
Huh, thanks, i thought the editor was only for making games, turns out i was wrong
